# Generated by Django 6.0.3 on 2026-06-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Professional', 'Professional')], default='Technical', max_length=20),
        ),
    ]
