# Generated by Django 6.0.3 on 2026-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('issue_date', models.DateField()),
            ],
        ),
    ]
