# Generated by Django 6.0.3 on 2026-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
